FROM python:3.10-slim

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        libglib2.0-0 \
        curl \
        && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY model_server_rf_requirements_type2.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt